#application.yml#spring.data.mongodb.host=localhost
#spring.data.mongodb.port = 27017
#spring.data.mongodb.uri = mongodb+srv://akashsahublue:EVYbTYSsVR8brjSN@cluster0.gn3ed.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring:

      mail:
        host: smtp.gmail.com
        port : 587
        username: akashsahuda.blue@gmail.com
        password : tbgp epck viia gvas
        properties :
          mail :
            smtp :
              auth : true
              starttls :
                enable : true

      data:
        mongodb:
        uri: mongodb+srv://akashsahublue:awdwefgagargar@aryson.gn3ed.mongodb.net/?retryWrites=true&w=majority&appName=Aryson
        #      uri : mongodb+srv://akashsahublue:<db_password>@cluster0.gn3ed.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        database: journaldb
        auto-index-creation: true



server:
  port: 8080
#  servlet:
#    context-path: /journal


data :
  api :
    key : Fsfgasgsagsafgaga


